version: "3.0"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: &img webimg
    command: gunicorn factionstats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file: ./env
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env.db
  nginx:
    build: ./nginx
    volumes:
      - user_html:/usr/src/app/user_html
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:latest
    expose:
      - 6379
  worker:
    image: *img
    command: celery -A factionstats worker --loglevel=info --concurrency=2
    env_file: ./env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  user_html: