version: "3.0"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: &img appimg
    command: gunicorn factionstats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file: ./env
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  redis:
    image: redis:latest
    expose:
      - 6379
  worker:
    image: *img
    command: celery -A factionstats worker --loglevel=warning --concurrency=2 --without-gossip --max-tasks-per-child=90
    env_file: ./env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: