# Generated by Django 2.2.4 on 2019-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='timestamp_hospital',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='timestamp_jail',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='defense',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='dexterity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='speed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='strength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
