# Generated by Django 2.2.4 on 2019-12-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20191005_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='status',
            new_name='status_desc',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='status2',
            new_name='status_details',
        ),
        migrations.AddField(
            model_name='target',
            name='status_state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
