# Generated by Django 2.2.4 on 2019-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20190821_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyreport',
            name='defense',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='dexterity',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='speed',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='strength',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spyreport',
            name='total',
            field=models.BigIntegerField(blank=True),
        ),
    ]
