# Generated by Django 2.2.4 on 2019-08-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keymanager', '0002_auto_20190817_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fsuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
